import MenuClient, { MenuCategory } from "@/components/MenuClient";

const MENU: MenuCategory[] = [
  {
    id: "tiffin",
    name: "Tiffin Treats",
    emoji: "🫓",
    tagline: "Classic South Indian breakfast, served all day",
    items: [
      { name: "Idly (3 pcs)", description: "Soft steamed rice cakes, chutney & sambar", isVeg: true },
      { name: "Medu Vada (3 pcs)", description: "Crispy lentil fritters", isVeg: true },
      { name: "Pongal", description: "Ghee-rich rice & lentil comfort bowl", isVeg: true },
      { name: "Upma", description: "Savory semolina with vegetables", isVeg: true },
      { name: "Poori (3 pcs)", description: "Fluffy fried bread with potato masala", isVeg: true },
      { name: "Mini Idly (12 pcs)", description: "Bite-sized idlies with sambar", isVeg: true },
      { name: "Sambar Idly (2 pcs)", description: "Idlies dipped in hot sambar", isVeg: true },
      { name: "Sambar Vada (2 pcs)", description: "Vadas soaked in sambar", isVeg: true },
      { name: "Mysore Bonda", isVeg: true },
      { name: "Pesarattu / Upma Pesarattu", isVeg: true },
      { name: "Millet Java", isVeg: true },
      { name: "Egg Dosa", description: "Thin dosa layered with egg", isVeg: false },
      { name: "Omelette", description: "Masala or plain", isVeg: false },
    ],
  },
  {
    id: "appetizers",
    name: "Appetizers",
    emoji: "🌶️",
    subSections: [
      {
        title: "Vegetarian",
        isVeg: true,
        items: [
          { name: "Pachi Mirchi Paneer Fry", description: "Fresh green chilli masala", isVeg: true },
          { name: "Pachi Mirchi Mushroom Fry", description: "Fiery green chilli mushrooms", isVeg: true },
          { name: "Pallipalayam Gobi", isVeg: true },
          { name: "Curry Leaf Paneer Fry", description: "Signature Balaji flavor", isVeg: true },
          { name: "Gobi 65", description: "Crispy cauliflower bites", isVeg: true },
          { name: "Baby Corn Manchurian", description: "Indo-Chinese favorite", isVeg: true },
          { name: "Water Chestnut Fry", description: "Unique, crunchy, premium", isVeg: true },
          { name: "Paneer Schezwan", description: "Spicy Indo-Chinese paneer", isVeg: true },
          { name: "Momos (5 Pcs / 10 Pcs)", isVeg: true },
          { name: "Veg Chili Momo (5 Pcs / 10 Pcs)", isVeg: true },
          { name: "Water Chestnut Manchurian", isVeg: true },
        ],
      },
      {
        title: "Non-Vegetarian",
        isVeg: false,
        items: [
          { name: "Pachi Mirchi Chicken Fry", description: "Green chilli chicken, bold & spicy", isVeg: false },
          { name: "Pachi Mirchi Shrimp Fry", description: "Jumbo shrimp in green chilli masala", isVeg: false },
          { name: "Chicken 65", description: "House special", isVeg: false },
          { name: "Dragon Chicken", isVeg: false },
          { name: "Chicken Sukka", description: "Semi-dry South Indian classic", isVeg: false },
          { name: "Apollo Fish", description: "Tangy Indo-Chinese fish", isVeg: false },
          { name: "Mutton Sukka", description: "Slow-roasted goat with spices", isVeg: false },
          { name: "Chicken Momos (Steamed/Fried)", description: "Himalayan dumplings", isVeg: false },
          { name: "Egg Puff", isVeg: false },
          { name: "Chicken Puff", isVeg: false },
          { name: "Chicken Lollipop (5 Pcs)", isVeg: false },
          { name: "Chili Chicken", isVeg: false },
          { name: "Karevapaku Chicken Fry", isVeg: false },
        ],
      },
    ],
  },
  {
    id: "dosa",
    name: "Dosa Junction",
    emoji: "🫔",
    tagline: "Thin, crispy & made to order",
    items: [
      { name: "Plain Dosa", isVeg: true },
      { name: "Ghee Dosa", isVeg: true },
      { name: "Masala Dosa", isVeg: true },
      { name: "Mysore Masala Dosa", isVeg: true },
      { name: "Curry Leaf Dosa", isVeg: true },
      { name: "Green Chilli Dosa", isVeg: true },
      { name: "Paneer Dosa", isVeg: true },
      { name: "Benne Dosa", isVeg: true },
      { name: "Andhra Karam Dosa", isVeg: true },
      { name: "Chocolate Dosa (Kids Special)", isVeg: true },
      { name: "Podi Dosa", isVeg: true },
      { name: "Egg Dosa", isVeg: false },
    ],
  },
  {
    id: "veg-curries",
    name: "Veg Curries",
    emoji: "🥘",
    tagline: "Rich, aromatic gravies",
    items: [
      { name: "Paneer Butter Masala", isVeg: true },
      { name: "Palak Paneer", isVeg: true },
      { name: "Kadai Paneer", isVeg: true },
      { name: "Navaratan Kurma", isVeg: true },
      { name: "Veg Kurma", isVeg: true },
      { name: "Dal Fry", isVeg: true },
    ],
  },
  {
    id: "nonveg-curries",
    name: "Non-Veg Curries",
    emoji: "🍗",
    tagline: "Bold flavors, slow-cooked",
    items: [
      { name: "Butter Chicken", isVeg: false },
      { name: "Chicken Chettinad", isVeg: false },
      { name: "Gongura Chicken", isVeg: false },
      { name: "Chicken Vindaloo", isVeg: false },
      { name: "Lamb Curry", isVeg: false },
      { name: "Shrimp Masala", isVeg: false },
      { name: "Godavari Chicken Curry", isVeg: false },
      { name: "Godavari Chepala Pulusu", isVeg: false },
      { name: "Godavari Shrimp & Eggs Pulusu", isVeg: false },
    ],
  },
  {
    id: "biryani",
    name: "Biryani",
    emoji: "🍚",
    tagline: "Slow-cooked, layered perfection",
    subSections: [
      {
        title: "Vegetarian",
        isVeg: true,
        items: [
          { name: "Paneer Biryani", isVeg: true },
          { name: "Jackfruit Biryani (Weekend)", isVeg: true },
          { name: "Ambur Soya Biryani", isVeg: true },
          { name: "Pachi Mirchi Paneer Pulao", isVeg: true },
          { name: "Kothimeera Paneer Pulao", isVeg: true },
          { name: "Labbipet Paneer Biryani", isVeg: true },
          { name: "Vijayawada Paneer Biryani", isVeg: true },
        ],
      },
      {
        title: "Non-Vegetarian",
        isVeg: false,
        items: [
          { name: "Labbipet Chicken Biryani", description: "Premium, yogurt-curd tomato base", isVeg: false },
          { name: "Labbipet Egg Biryani", isVeg: false },
          { name: "Hyderabadi Chicken Dum Biryani", isVeg: false },
          { name: "Ambur Chicken Biryani", isVeg: false },
          { name: "Ambur Mutton Biryani", isVeg: false },
          { name: "Ulavacharu Chicken Biryani", isVeg: false },
          { name: "Gongura Chicken Biryani", isVeg: false },
          { name: "Gongura Goat Biryani", isVeg: false },
          { name: "Ghee Roast Goat Biryani", isVeg: false },
          { name: "Shahi Gosht Biryani", isVeg: false },
          { name: "RJY Chicken Fry Piece Biryani", isVeg: false },
        ],
      },
    ],
  },
  {
    id: "meals",
    name: "Meals / Thali",
    emoji: "🍽️",
    tagline: "A complete spread, every time",
    subSections: [
      {
        title: "Veg",
        isVeg: true,
        items: [
          {
            name: "Regular Veg Meals",
            description: "Variety rice, rottipachadi, veg fry, veg curry, dal, curd",
            isVeg: true,
          },
          { name: "Special Veg Meals (Weekend)", isVeg: true },
        ],
      },
      {
        title: "Non-Veg",
        isVeg: false,
        items: [
          { name: "Regular Non-Veg Meals", isVeg: false },
          { name: "Special Non-Veg Meals (Weekend)", isVeg: false },
        ],
      },
    ],
  },
  {
    id: "specialities",
    name: "Signature Specialities",
    emoji: "⭐",
    tagline: "Our house originals",
    items: [
      { name: "Paal Parotta", description: "Chicken / Mutton / Egg", isVeg: false },
      { name: "Kotthu Parotta", description: "Veg / Chicken / Egg", isVeg: false },
      { name: "Parotta Salna", isVeg: true },
      { name: "Parotta", description: "Chicken gravy / Mutton gravy", isVeg: false },
    ],
  },
  {
    id: "snacks",
    name: "Evening Snacks",
    emoji: "🍟",
    tagline: "4 PM – 9 PM · Fried fresh to order",
    items: [
      { name: "Masala Vada", isVeg: true },
      { name: "Onion Pakoda", isVeg: true },
      { name: "Mirchi Bajji", isVeg: true },
      { name: "Pungulu", isVeg: true },
      { name: "Samosas (Onion/Potato)", isVeg: true },
      { name: "Vazhakkai Bajji", isVeg: true },
      { name: "Spinach Pakora", isVeg: true },
      { name: "Soya Pakora", isVeg: true },
      { name: "Challa Baji", isVeg: true },
      { name: "Egg Bonda", isVeg: false },
    ],
  },
  {
    id: "bread-rice",
    name: "Bread & Rice",
    emoji: "🫓",
    tagline: "Baked fresh in the tandoor",
    items: [
      { name: "Plain Naan / Butter Naan", isVeg: true },
      { name: "Garlic Naan", isVeg: true },
      { name: "Chili Naan", isVeg: true },
      { name: "Tandoori Roti", isVeg: true },
      { name: "Bread Basket", isVeg: true },
      { name: "Plain Rice", isVeg: true },
      { name: "Parotta", isVeg: true },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    emoji: "🍮",
    tagline: "Sweet endings",
    items: [
      { name: "Gulab Jamun", isVeg: true },
      { name: "Ras Malai", isVeg: true },
      { name: "Double Ka Meetha", isVeg: true },
      { name: "Sweet Pan", isVeg: true },
    ],
  },
  {
    id: "drinks",
    name: "Drinks",
    emoji: "☕",
    tagline: "Hot & cold, brewed with care",
    items: [
      { name: "Filter Coffee", isVeg: true },
      { name: "Masala Tea", isVeg: true },
      { name: "Mango Lassi", isVeg: true },
      { name: "Rose Milk", isVeg: true },
      { name: "Masala Buttermilk", isVeg: true },
      { name: "Elaineer Sarbath", description: "Signature coconut drink", isVeg: true },
    ],
  },
];

export default function MenuPage() {
  return <MenuClient categories={MENU} />;
}
