import MenuClient, { MenuCategory } from "@/components/MenuClient";

const MENU: MenuCategory[] = [
  {
    id: "tiffin",
    name: "Tiffin Treats",
    emoji: "🥣",
    tagline: "Classic South Indian breakfast, served all day",
    items: [
      { name: "Plain Idly (3 pcs)", price: "$7.99", isVeg: true },
      { name: "Mini Ghee Podi Idly", price: "$8.49", isVeg: true },
      { name: "Sambar Idly (2 pcs)", price: "$7.99", isVeg: true },
      { name: "Mini Idly (10 pcs)", price: "$8.99", isVeg: true },
      { name: "Mega Combo", description: "1 Idly, Pongal, 1 Dosa, 1 Vada", price: "$13.99", isVeg: true },
      { name: "Medu Vada (3 pcs)", price: "$8.99", isVeg: true },
      { name: "Ven Pongal", price: "$8.49", isVeg: true },
    ],
  },
  {
    id: "dosa",
    name: "Dosa Junction",
    emoji: "🔥",
    tagline: "Crisp, golden, handcrafted dosas",
    items: [
      { name: "Plain Dosa", price: "$9.99", isVeg: true },
      { name: "Podi Dosa", price: "$10.99", isVeg: true },
      { name: "Ghee Dosa", price: "$11.99", isVeg: true },
      { name: "Benne Dosa", price: "$11.99", isVeg: true },
      { name: "Masala Dosa", price: "$13.99", isVeg: true },
      { name: "Mysore Masala Dosa", price: "$13.99", isVeg: true },
      { name: "Curry Leaf Dosa", price: "$13.99", isVeg: true },
      { name: "Green Chilli Dosa", price: "$13.99", isVeg: true },
      { name: "Andhra Kara Dosa", price: "$13.99", isVeg: true },
      { name: "Paneer Dosa", price: "$13.99", isVeg: true },
      { name: "Egg Dosa", price: "$13.49", isVeg: false },
      { name: "Uthappam", description: "Onion / Chilli / Tomato / Mixed", price: "$14.49", isVeg: true },
      { name: "Kids Dosa", description: "Chocolate (Nutella) Dosa", price: "$9.99", isVeg: true },
      { name: "Cone Dosa", price: "$9.99", isVeg: true },
    ],
  },
  {
    id: "parotta",
    name: "Parotta Zone",
    emoji: "🫓",
    tagline: "Flaky, layered, and loaded with flavor",
    items: [
      { name: "Egg Paal Parotta", price: "$13.99", isVeg: false },
      { name: "Chicken Paal Parotta", price: "$14.99", isVeg: false },
      { name: "Goat Paal Parotta", price: "$15.99", isVeg: false },
      { name: "Veg Kothu Parotta", price: "$13.99", isVeg: true },
      { name: "Egg Kothu Parotta", price: "$13.99", isVeg: false },
      { name: "Chicken Kothu Parotta", price: "$14.99", isVeg: false },
      { name: "Goat Kothu Parotta", price: "$15.99", isVeg: false },
      { name: "Kizhi Parotta", price: "$13.99", isVeg: true },
      { name: "Parotta with Veg Salna", price: "$10.99", isVeg: true },
      { name: "Parotta with Chicken Gravy", price: "$11.99", isVeg: false },
      { name: "Parotta with Goat Gravy", price: "$12.99", isVeg: false },
      { name: "Plain Parotta (2 pcs)", price: "$3.49", isVeg: true },
    ],
  },
  {
    id: "starters",
    name: "Starters",
    emoji: "🍢",
    subSections: [
      {
        title: "Vegetarian",
        isVeg: true,
        items: [
          { name: "Paneer 65 Fry", price: "$12.99", isVeg: true },
          { name: "Paneer Curry Leaf", price: "$13.99", isVeg: true },
          { name: "Paneer Pachi Mirchi", price: "$13.99", isVeg: true },
          { name: "Paneer Manchurian", price: "$12.99", isVeg: true },
          { name: "Paneer Gongura", price: "$14.99", isVeg: true },
          { name: "Gobi 65 Fry", price: "$12.99", isVeg: true },
          { name: "Baby Corn 65 Fry", price: "$12.99", isVeg: true },
          { name: "Gobi Pachi Mirchi", price: "$13.99", isVeg: true },
          { name: "Gobi Manchurian", price: "$12.99", isVeg: true },
          { name: "Chilli Baby Corn", price: "$13.99", isVeg: true },
        ],
      },
      {
        title: "Non-Vegetarian",
        isVeg: false,
        items: [
          { name: "Chicken Sukka Fry", price: "$12.99", isVeg: false },
          { name: "Chicken 65 Fry", price: "$12.99", isVeg: false },
          { name: "Chilli Chicken", price: "$12.99", isVeg: false },
          { name: "Curry Leaf Chicken", price: "$13.99", isVeg: false },
          { name: "Pachi Mirchi Chicken", price: "$13.99", isVeg: false },
          { name: "Pepper Chicken", price: "$13.99", isVeg: false },
          { name: "Chicken Manchurian", price: "$12.99", isVeg: false },
          { name: "Gongura Chicken", price: "$14.99", isVeg: false },
          { name: "Shrimp 65 Fry", price: "$12.99", isVeg: false },
          { name: "Pachi Mirchi Shrimp", price: "$13.99", isVeg: false },
          { name: "Pepper Shrimp", price: "$13.99", isVeg: false },
          { name: "Curry Leaf Shrimp", price: "$13.99", isVeg: false },
          { name: "Goat Sukka Fry", price: "$13.99", isVeg: false },
          { name: "Goat Ghee Roast", price: "$14.99", isVeg: false },
          { name: "Gongura Goat", price: "$15.99", isVeg: false },
          { name: "Tawa Fish Fry", price: "$13.99", isVeg: false },
          { name: "Chilli Fish Fry", price: "$13.99", isVeg: false },
          { name: "Polichedu Fish Fry", price: "$15.99", isVeg: false },
          { name: "Egg Varuval", price: "$6.99", isVeg: false },
          { name: "Egg Podimas", price: "$6.99", isVeg: false },
          { name: "Egg Kalaki", price: "$6.99", isVeg: false },
          { name: "Omelette", price: "$6.99", isVeg: false },
          { name: "Boiled Egg", price: "$2.99", isVeg: false },
        ],
      },
    ],
  },
  {
    id: "curries",
    name: "Curries",
    emoji: "🍛",
    tagline: "Rich, aromatic gravies",
    subSections: [
      {
        title: "Vegetarian",
        isVeg: true,
        items: [
          { name: "Paneer Curry", price: "$14.49", isVeg: true },
          { name: "Paneer Butter Masala", price: "$14.49", isVeg: true },
          { name: "Palak Paneer", price: "$14.49", isVeg: true },
          { name: "Kadai Paneer", price: "$14.49", isVeg: true },
          { name: "Veg Kurma", price: "$12.99", isVeg: true },
          { name: "Spinach Dal Fry", price: "$10.99", isVeg: true },
          { name: "Tomato Dal Fry", price: "$10.99", isVeg: true },
          { name: "Gongura Dal Fry", price: "$11.99", isVeg: true },
        ],
      },
      {
        title: "Non-Vegetarian",
        isVeg: false,
        items: [
          { name: "Chicken Curry", price: "$13.99", isVeg: false },
          { name: "Butter Chicken Curry", price: "$13.99", isVeg: false },
          { name: "Chettinad Chicken Curry", price: "$13.99", isVeg: false },
          { name: "Kadai Chicken Curry", price: "$13.99", isVeg: false },
          { name: "Gongura Chicken Curry", price: "$13.99", isVeg: false },
          { name: "Seafood Curry", price: "$14.99", isVeg: false },
          { name: "Shrimp Masala Curry", price: "$14.99", isVeg: false },
          { name: "Fish Curry", price: "$14.99", isVeg: false },
          { name: "Goat Curry", price: "$18.99", isVeg: false },
          { name: "Gongura Goat Curry", price: "$18.99", isVeg: false },
          { name: "Egg Curry", price: "$10.99", isVeg: false },
        ],
      },
    ],
  },
  {
    id: "biryani",
    name: "Biryani",
    emoji: "🍽️",
    tagline: "Slow-cooked, layered perfection",
    subSections: [
      {
        title: "Vegetarian",
        isVeg: true,
        items: [
          { name: "Ambur Jackfruit Biryani", price: "$14.99", isVeg: true },
          { name: "Veg Biryani", price: "$14.99", isVeg: true },
        ],
      },
      {
        title: "Non-Vegetarian",
        isVeg: false,
        items: [
          { name: "Egg Biryani", price: "$14.99", isVeg: false },
          { name: "Hyderabadi Biryani", description: "Weekend Special", price: "$14.99", isVeg: false },
          { name: "Ambur Chicken Biryani", price: "$14.99", isVeg: false },
          { name: "Ambur Goat Biryani", price: "$16.99", isVeg: false },
        ],
      },
    ],
  },
  {
    id: "snacks",
    name: "Street Snacks",
    emoji: "🍟",
    tagline: "Quick bites, big flavor",
    items: [
      { name: "Samosa", price: "$5.99", isVeg: true },
      { name: "Punugulu", price: "$5.99", isVeg: true },
    ],
  },
  {
    id: "desserts",
    name: "Desserts & Beverages",
    emoji: "🍰",
    tagline: "Sweet endings, refreshing sips",
    subSections: [
      {
        title: "Desserts",
        isVeg: true,
        items: [
          { name: "Rava Kesari", price: "$3.00", isVeg: true },
          { name: "Gulab Jamun", price: "$3.00", isVeg: true },
          { name: "Ras Malai", price: "$3.00", isVeg: true },
          { name: "Sweet Pan", price: "$3.00", isVeg: true },
        ],
      },
      {
        title: "Cool Zone",
        isVeg: true,
        items: [
          { name: "Rose Milk", price: "$3.00", isVeg: true },
          { name: "Mango Lassi", price: "$3.00", isVeg: true },
          { name: "Majjiga", description: "Buttermilk", price: "$3.00", isVeg: true },
          { name: "Badam Milk", price: "$3.00", isVeg: true },
        ],
      },
      {
        title: "Tea & Coffee",
        isVeg: true,
        items: [
          { name: "Masala Tea", price: "$2.99", isVeg: true },
          { name: "Hamaara Special Coffee", price: "$3.49", isVeg: true },
        ],
      },
    ],
  },
];

export default function MenuPage() {
  return <MenuClient categories={MENU} />;
}
