import MenuClient, { MenuCategory } from "@/components/MenuClient";

const MENU: MenuCategory[] = [
  {
    id: "tiffins",
    name: "Tiffins",
    emoji: "🥣",
    tagline: "Classic South Indian breakfast, served all day",
    items: [
      { name: "Plain Idly (2 pcs)", price: "$7.49", isVeg: true },
      { name: "Ghee Karam Idly (2 pcs)", price: "$9.49", isVeg: true },
      { name: "Trump Idly (10 pcs)", price: "$9.99", isVeg: true },
      { name: "Sambar Idly", price: "$8.99", isVeg: true },
      { name: "Vada (2 pcs)", price: "$7.49", isVeg: true },
      { name: "Sambar Vada (2 pcs)", price: "$8.49", isVeg: true },
      { name: "Plain Dosa", price: "$8.99", isVeg: true },
      { name: "Modi Masala Dosa", price: "$10.99", isVeg: true },
      { name: "Onion Dosa", price: "$9.99", isVeg: true },
      { name: "Pesarattu Upma", price: "$11.49", isVeg: true },
      { name: "Set Dosa", price: "$10.49", isVeg: true },
      { name: "Benne Masala Dosa", price: "$11.99", isVeg: true },
      { name: "Plain Ravva Dosa", price: "$9.99", isVeg: true },
      { name: "Onion Ravva Dosa", price: "$10.99", isVeg: true },
      { name: "Masala Ravva Dosa", price: "$11.49", isVeg: true },
      { name: "Plain Uthappam", price: "$9.49", isVeg: true },
      { name: "Onion Uthappam", price: "$9.99", isVeg: true },
      { name: "Puri With Aloo Masala (2 pcs)", price: "$8.89", isVeg: true },
      { name: "Puri (1 pc)", price: "$3.39", isVeg: true },
      { name: "Mysore Bonda (4 pcs)", price: "$8.89", isVeg: true },
      { name: "Kim Karabath", price: "$8.89", isVeg: true },
    ],
  },
  {
    id: "appetizers",
    name: "Appetizers",
    emoji: "🍢",
    tagline: "Crispy starters to kick things off",
    items: [
      { name: "Aloo Samosa (2 pcs)", price: "$5.49", isVeg: true },
      { name: "Onion Samosa (4 pcs)", price: "$5.99", isVeg: true },
      { name: "Gobi Manchurian", price: "$11.99", isVeg: true },
      { name: "Baby Corn Manchurian", price: "$12.49", isVeg: true },
      { name: "Pepper Mushroom Fry", price: "$12.49", isVeg: true },
      { name: "Pepper Babycorn Fry", price: "$12.49", isVeg: true },
      { name: "Paneer 555", price: "$13.49", isVeg: true },
      { name: "Paneer Manchurian", price: "$13.49", isVeg: true },
      { name: "Veg Manchurian", price: "$11.99", isVeg: true },
    ],
  },
  {
    id: "indo-chinese",
    name: "Indo Chinese",
    emoji: "🍜",
    tagline: "Fusion flavors with an Indian twist",
    items: [
      { name: "Veg Fried Rice", price: "$11.99", isVeg: true },
      { name: "Schezwan Rice", price: "$12.99", isVeg: true },
      { name: "Jeera Rice", price: "$8.99", isVeg: true },
      { name: "Veg Noodles", price: "$11.99", isVeg: true },
      { name: "Schezwan Noodles", price: "$12.99", isVeg: true },
    ],
  },
  {
    id: "combos",
    name: "Combos",
    emoji: "🤝",
    tagline: "Best value combinations",
    items: [
      { name: "1 Idly 1 Vada", price: "$8.99", isVeg: true },
      { name: "1 Idly 1 Vada With Pongal Or Upma", price: "$10.99", isVeg: true },
    ],
  },
  {
    id: "kids",
    name: "Star Kids Menu — Dosa Specials",
    emoji: "⭐",
    tagline: "Fun dosas for the little ones",
    items: [
      { name: "Chocolate Dosa", price: "$9.49", isVeg: true },
      { name: "Pizza Dosa", price: "$9.49", isVeg: true },
      { name: "Cheese Dosa", price: "$9.49", isVeg: true },
    ],
  },
  {
    id: "bandi-ruchulu",
    name: "Bandi Ruchulu",
    emoji: "🛒",
    tagline: "Street-style specials • 5 PM – 9 PM",
    items: [
      { name: "Mirchi Bajji (4 pcs)", price: "$8.49", isVeg: true },
      { name: "Stuffed Mirchi (4 pcs)", price: "$9.99", isVeg: true },
      { name: "Cut Mirchi Bajji (10 pcs)", price: "$8.49", isVeg: true },
      { name: "Vijayawada Punugulu", price: "$8.99", isVeg: true },
      { name: "Nalla Karam Punugulu", price: "$9.49", isVeg: true },
    ],
  },
  {
    id: "pulavs",
    name: "Pulav's",
    emoji: "🍚",
    tagline: "Fragrant, hearty rice dishes",
    items: [
      { name: "Veg Pulav", price: "$11.99", isVeg: true },
      { name: "Jackfruit Pulav", price: "$12.99", isVeg: true },
      { name: "Gongura Paneer Pulav", price: "$13.99", isVeg: true },
      { name: "Pachimirchi Paneer Pulav", price: "$13.99", isVeg: true },
      { name: "Guthivankaya Pulav", price: "$12.99", isVeg: true },
    ],
  },
  {
    id: "biryanis",
    name: "Biryani's",
    emoji: "🍽️",
    tagline: "Slow-cooked, layered perfection",
    items: [
      { name: "Veg Dum Biryani", price: "$12.99", isVeg: true },
      { name: "Ulavacharu Biryani", price: "$13.99", isVeg: true },
      { name: "Paneer Biryani", price: "$14.49", isVeg: true },
    ],
  },
  {
    id: "curries",
    name: "Veg Curries",
    emoji: "🍛",
    tagline: "Served with 2 pulkas",
    items: [
      { name: "Paneer Butter Masala", price: "$13.99", isVeg: true },
      { name: "Paneer Tikka Masala", price: "$13.99", isVeg: true },
      { name: "Paneer Cashew", price: "$14.49", isVeg: true },
      { name: "Dal Tadka", price: "$11.99", isVeg: true },
      { name: "Aloo Gobi", price: "$11.99", isVeg: true },
      { name: "Methi Chaman", price: "$13.99", isVeg: true },
    ],
  },
  {
    id: "bhojanam",
    name: "Amrutham Special Bhojanam",
    emoji: "🌿",
    tagline: "Traditional thali • 12 PM – 3 PM",
    items: [
      { name: "Agraharam Bhojanam", price: "$16.99", isVeg: true },
      { name: "Office Special Bhojanam", price: "$12.99", isVeg: true },
    ],
  },
  {
    id: "beverages",
    name: "Hot & Cold Beverages",
    emoji: "☕",
    tagline: "Refreshing sips to end your meal",
    items: [
      { name: "Hyderbad Chai", price: "$2.99", isVeg: true },
      { name: "Chennai Filter Coffee", price: "$3.99", isVeg: true },
      { name: "Bandar Badam Milk", price: "$4.49", isVeg: true },
      { name: "Rajahmundry Rose Milk", price: "$4.49", isVeg: true },
      { name: "Mango Lassi", price: "$4.49", isVeg: true },
    ],
  },
];

export default function MenuPage() {
  return <MenuClient categories={MENU} />;
}
